baseURL = '/'
languageCode = 'en-us'
title = 'My New Hugo Site'
theme = "paper"
publishDir = "docs"

disqusShortname = 'YOUR_DISQUS_SHORTNAME'   # add disqus comments

[params]
  disableHLJS = true                         # don't use highlight.js
  twitter = 'YOUR_TWITTER_ID'                # twitter.com/YOUR_TWITTER_ID
  github = 'YOUR_GITHUB_ID'                  # github.com/YOUR_GITHUB_ID
  instagram = 'YOUR_INSTAGRAM_ID'            # instagram.com/YOUR_INSTAGRAM_ID
